# Generated by Django 4.0.5 on 2022-12-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='image',
        ),
    ]
