# Generated by Django 4.0.5 on 2022-12-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_users', '0002_rename_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
